modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/easy-villagers/issues"
[[mods]]
modId = "easy_villagers"
version = "${mod_version}"
displayName = "Easy Villagers"
updateJSONURL = "https://update.maxhenkel.de/neoforge/easy_villagers"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/easy-villagers"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''Easy Villagers'''
[[dependencies.easy_villagers]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.easy_villagers]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.easy_villagers]]
modId = "jei"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.easy_villagers]]
modId = "theoneprobe"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.easy_villagers]]
modId = "jade"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"